# Configuración del proyecto Django en SonarQube

sonar.projectKey=proyectoint
sonar.projectName=Proyecto Integrado Django
sonar.projectVersion=1.0

# Carpeta raíz del código
sonar.sources=.

# Lenguaje principal
sonar.language=py

# URL de tu SonarQube local
sonar.host.url=http://localhost:9000

# Token de autenticación (nuevo formato)
sonar.token=squ_7529f65385fb101968a0f7707dbee734376c6cbb


