# Generated by Django 5.2.7 on 2025-10-23 19:19

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0002_farmacia_telefono_motorista_direccion_motorista_rut_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comuna',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Provincia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Region',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='moto',
            name='motorista',
        ),
        migrations.RemoveField(
            model_name='motorista',
            name='nombre_completo',
        ),
        migrations.AddField(
            model_name='farmacia',
            name='horario_apertura',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='farmacia',
            name='horario_cierre',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='farmacia',
            name='latitud',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True),
        ),
        migrations.AddField(
            model_name='farmacia',
            name='longitud',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True),
        ),
        migrations.AddField(
            model_name='moto',
            name='anio',
            field=models.IntegerField(blank=True, null=True, verbose_name='Año'),
        ),
        migrations.AddField(
            model_name='moto',
            name='color',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='moto',
            name='es_propiedad_empresa',
            field=models.BooleanField(default=True, verbose_name='Propietario Moto (Empresa=Sí)'),
        ),
        migrations.AddField(
            model_name='moto',
            name='marca',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='moto',
            name='motor',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='moto',
            name='motorista_asignado',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='motos_asignadas', to='App.motorista'),
        ),
        migrations.AddField(
            model_name='moto',
            name='numero_chasis',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='motorista',
            name='apellido_materno',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='motorista',
            name='apellido_paterno',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='motorista',
            name='fecha_nacimiento',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='motorista',
            name='incluye_moto_personal',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='motorista',
            name='licencia_archivo',
            field=models.FileField(blank=True, null=True, upload_to='licencias/', verbose_name='Adjunto Licencia'),
        ),
        migrations.AddField(
            model_name='motorista',
            name='licencia_ultimo_control',
            field=models.DateField(blank=True, null=True, verbose_name='Fecha Último Control Licencia'),
        ),
        migrations.AddField(
            model_name='motorista',
            name='nombres',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='motorista',
            name='pasaporte',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='farmacia',
            name='nombre',
            field=models.CharField(max_length=100, verbose_name='Nombre farmacia'),
        ),
        migrations.AlterField(
            model_name='moto',
            name='patente',
            field=models.CharField(max_length=10, unique=True, verbose_name='Patente/Matrícula'),
        ),
        migrations.AlterField(
            model_name='motorista',
            name='email',
            field=models.EmailField(max_length=254, unique=True, verbose_name='Correo electrónico'),
        ),
        migrations.AlterField(
            model_name='motorista',
            name='rut',
            field=models.CharField(blank=True, max_length=12, null=True, unique=True, validators=[django.core.validators.RegexValidator(message='El RUT debe tener el formato XX.XXX.XXX-X', regex='^\\d{1,2}\\.\\d{3}\\.\\d{3}-[\\dkK]$')]),
        ),
        migrations.AddField(
            model_name='farmacia',
            name='comuna',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='App.comuna'),
        ),
        migrations.AddField(
            model_name='motorista',
            name='comuna',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='App.comuna'),
        ),
        migrations.CreateModel(
            name='ContactoEmergencia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_contacto', models.CharField(max_length=100)),
                ('parentesco', models.CharField(blank=True, max_length=50, null=True)),
                ('telefono', models.CharField(max_length=20)),
                ('motorista', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contactos_emergencia', to='App.motorista')),
            ],
        ),
        migrations.AddField(
            model_name='comuna',
            name='provincia',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='App.provincia'),
        ),
        migrations.AddField(
            model_name='provincia',
            name='region',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='App.region'),
        ),
        migrations.CreateModel(
            name='DocumentacionMoto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('anio', models.IntegerField(verbose_name='Año Documentación')),
                ('permiso_circulacion', models.FileField(blank=True, null=True, upload_to='docs_moto/permisos/')),
                ('seguro_obligatorio', models.FileField(blank=True, null=True, upload_to='docs_moto/seguros/')),
                ('revision_tecnica', models.FileField(blank=True, null=True, upload_to='docs_moto/revisiones/')),
                ('moto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documentaciones', to='App.moto')),
            ],
            options={
                'unique_together': {('moto', 'anio')},
            },
        ),
    ]
