# Generated by Django 5.2.7 on 2025-10-30 19:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0003_comuna_provincia_region_remove_moto_motorista_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='TipoMovimiento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Movimiento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('observacion', models.TextField(blank=True, null=True, verbose_name='Observación')),
                ('fecha_hora', models.DateTimeField(auto_now_add=True, verbose_name='Fecha y Hora')),
                ('farmacia', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='App.farmacia', verbose_name='Farmacia')),
                ('motorista', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='App.motorista', verbose_name='Motorista')),
                ('tipo_movimiento', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='App.tipomovimiento', verbose_name='Tipo de Movimiento')),
            ],
        ),
        migrations.CreateModel(
            name='Asignacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_asignacion', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Asignación')),
                ('farmacia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='App.farmacia', verbose_name='Farmacia Asignada')),
                ('motorista', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='App.motorista', verbose_name='Motorista Asignado')),
            ],
            options={
                'unique_together': {('motorista', 'farmacia')},
            },
        ),
    ]
