# Generated by Django 5.2.7 on 2025-10-31 00:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0005_motorista_esta_activo_motorista_reemplaza_a'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='motorista',
            name='esta_activo',
        ),
        migrations.RemoveField(
            model_name='motorista',
            name='reemplaza_a',
        ),
        migrations.AddField(
            model_name='movimiento',
            name='motorista_original',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='movimientos_reemplazados', to='App.motorista', verbose_name='Motorista Original (si fue reemplazado)'),
        ),
        migrations.AddField(
            model_name='movimiento',
            name='status',
            field=models.CharField(choices=[('asignado', 'Asignado'), ('en_ruta', 'En Ruta'), ('entregado', 'Entregado'), ('fallido', 'Fallido')], default='asignado', max_length=20, verbose_name='Estado'),
        ),
        migrations.AlterField(
            model_name='movimiento',
            name='motorista',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='App.motorista', verbose_name='Motorista (Actual)'),
        ),
    ]
