# Generated by Django 5.2.7 on 2025-10-31 01:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0006_remove_motorista_esta_activo_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='motorista',
            name='esta_activo',
            field=models.BooleanField(default=True, verbose_name='Está Activo'),
        ),
        migrations.AddField(
            model_name='motorista',
            name='reemplaza_a',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reemplazado_por', to='App.motorista', verbose_name='Reemplaza a'),
        ),
    ]
