# Generated by Django 5.2.7 on 2025-11-04 13:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0007_motorista_esta_activo_motorista_reemplaza_a'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movimiento',
            name='status',
            field=models.CharField(choices=[('asignado', 'Asignado'), ('en_ruta', 'En Ruta'), ('entregado', 'Entregado'), ('fallido', 'Fallido'), ('anulado', 'Anulado')], default='asignado', max_length=20, verbose_name='Estado'),
        ),
    ]
