# Generated by Django 5.2.7 on 2025-11-05 03:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0008_alter_movimiento_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='movimiento',
            name='farmacia_destino',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='movimientos_destino', to='App.farmacia', verbose_name='Farmacia Destino (solo traslados)'),
        ),
        migrations.AlterField(
            model_name='movimiento',
            name='farmacia',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='App.farmacia', verbose_name='Farmacia Origen'),
        ),
    ]
