# Generated by Django 5.2.7 on 2025-11-11 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0009_movimiento_farmacia_destino_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movimiento',
            name='status',
            field=models.CharField(choices=[('en_ruta', 'En Ruta'), ('entregado', 'Entregado'), ('fallido', 'Fallido'), ('anulado', 'Anulado')], default='en_ruta', max_length=20, verbose_name='Estado'),
        ),
    ]
