# Generated by Django 5.2.7 on 2025-11-25 20:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0010_alter_movimiento_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='Reporte',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('observacion', models.TextField(help_text='Conclusiones finales o detalles de la entrega.', verbose_name='Observación del Reporte')),
                ('fecha_generacion', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Generación')),
                ('movimiento', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='reporte', to='App.movimiento')),
            ],
        ),
    ]
