"""
Django settings for proyectoint project.

Generated by 'django-admin startproject' using Django 5.2.7.
"""

import os
from pathlib import Path

# --- BASE DIR ---
BASE_DIR = Path(__file__).resolve().parent.parent
TEMPLATES_DIR = os.path.join(BASE_DIR, 'templates')

# --- SECURITY ---
SECRET_KEY = 'django-insecure-fl-#6n1(fhi3621l!c#@govraetn$n=$ellm8v6$-kg6^ouauc'
DEBUG = True
ALLOWED_HOSTS = []


# --- APPS INSTALADAS ---
INSTALLED_APPS = [
    'jazzmin',
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',

    'crispy_forms',
    'crispy_bootstrap5',

    'App',
]


# --- MIDDLEWARE (ORDEN CORRECTO + CUSTOM) ---
MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',

    #  MIDDLEWARE PERSONALIZADO PARA EXPIRAR SESIÓN
    'App.middleware.SessionExpiryMiddleware',

    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]


# --- URLS ---
ROOT_URLCONF = 'proyectoint.urls'


# --- TEMPLATES ---
TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [TEMPLATES_DIR],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]


# --- WSGI ---
WSGI_APPLICATION = 'proyectoint.wsgi.application'


# --- BASE DE DATOS ---
DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.mysql',
        'NAME': 'logico_db',
        'USER': 'logico_user',
        'PASSWORD': 'Kevin123',
        'HOST': 'localhost',
        'PORT': '3306',
        'OPTIONS': {
            'init_command': "SET sql_mode='STRICT_TRANS_TABLES'",
        },
    }
}


# --- VALIDACIÓN DE CONTRASEÑAS ---
AUTH_PASSWORD_VALIDATORS = [
    {'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator'},
    {'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator'},
    {'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator'},
    {'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator'},
]


# --- INTERNACIONALIZACIÓN ---
LANGUAGE_CODE = 'es-cl'
TIME_ZONE = 'America/Santiago'
USE_I18N = True
USE_TZ = True


# --- STATIC FILES ---
STATIC_URL = 'static/'
STATICFILES_DIRS = [os.path.join(BASE_DIR, 'static')]


# --- MEDIA FILES ---
MEDIA_URL = '/media/'
MEDIA_ROOT = os.path.join(BASE_DIR, 'media')


# --- DEFAULT PK ---
DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'


# --- JAZZMIN ---
JAZZMIN_SETTINGS = {
    "site_title": "Logico Admin",
    "site_header": "Logico",
    "site_brand": "Logico",
    "welcome_sign": "Bienvenido a la Administración de Logico",
    "copyright": "Logico App",
    "actions_on_top": True,
}


# --- CRISPY FORMS ---
CRISPY_ALLOWED_TEMPLATE_PACKS = "bootstrap5"
CRISPY_TEMPLATE_PACK = "bootstrap5"


# --- LOGIN / LOGOUT REDIRECT ---
LOGIN_REDIRECT_URL = 'home'
LOGOUT_REDIRECT_URL = 'login'


# --- EMAIL (DESARROLLO) ---
EMAIL_BACKEND = 'django.core.mail.backends.console.EmailBackend'


# ----------------------------------------------------
# CONFIGURACIÓN COMPLETA DE EXPIRACIÓN DE SESIÓN
# ----------------------------------------------------

# 1) La sesión expira al cerrar navegador
SESSION_EXPIRE_AT_BROWSER_CLOSE = True

# 2) Tiempo máximo de inactividad (5 minutos)
SESSION_COOKIE_AGE = 300  # 300 segundos = 5 minutos

# 3) Se renueva cada request
SESSION_SAVE_EVERY_REQUEST = True

# 4) Mensaje para mostrar al usuario
SESSION_EXPIRED_MESSAGE = "Tu sesión ha expirado por inactividad. Por favor inicia sesión nuevamente."

